owncloud/docs-client-desktop

modules/ROOT/pages/advanced_usage/command_line_options.adoc, modules/ROOT/pages/building.adoc, modules/ROOT/pages/troubleshooting.adoc
Make a 2.7 branch which is the actual shipped version
=> Make a 2.7 branch which is the actual shipped version

modules/ROOT/pages/building.adoc
Improve `building.adoc` by using attributes and fixing some text.
Backport to 2.8
=> Improve building.adoc

bin/find-orphaned-files.sh, bin/instructions_makepdf.md, bin/linter, bin/makepdf, bin/yamlparse.sh, bin/yamltest.sh, books/ownCloud_Desktop_Client_Manual.adoc, modules/ROOT/nav.adoc, modules/ROOT/pages/advanced_usage/index.adoc, modules/ROOT/pages/appendices/architecture.adoc, modules/ROOT/pages/appendices/building.adoc, modules/ROOT/pages/appendices/index.adoc, modules/ROOT/pages/appendices/troubleshooting.adoc, modules/ROOT/pages/installing.adoc
This adds the bin directory as we have in docs.
Most important, we have now a working pdf generation 😄 
Some doc fixes were necessary, found during debugging
The instruction file for the makepdf script needs more content
The linter is not working and just a placeholder - needs some work
MOST IMPORTANT currently no drone integration. This will come with another PR which then also drops the Makefile (only kept to ease the drone integration)
=> Add bin directory with makepdf

bin/find-orphaned-files.sh, bin/instructions_makepdf.md, bin/linter, bin/makepdf, bin/yamlparse.sh, bin/yamltest.sh, books/ownCloud_Desktop_Client_Manual.adoc, modules/ROOT/nav.adoc, modules/ROOT/pages/advanced_usage/index.adoc, modules/ROOT/pages/appendices/architecture.adoc, modules/ROOT/pages/appendices/building.adoc, modules/ROOT/pages/appendices/index.adoc, modules/ROOT/pages/appendices/troubleshooting.adoc, modules/ROOT/pages/installing.adoc
=> [2.7] [PR 13] Add bin directory with makepdf

bin/find-orphaned-files.sh, bin/instructions_makepdf.md, bin/linter, bin/makepdf, bin/yamlparse.sh, bin/yamltest.sh, books/ownCloud_Desktop_Client_Manual.adoc, modules/ROOT/nav.adoc, modules/ROOT/pages/advanced_usage/index.adoc, modules/ROOT/pages/appendices/architecture.adoc, modules/ROOT/pages/appendices/building.adoc, modules/ROOT/pages/appendices/index.adoc, modules/ROOT/pages/appendices/troubleshooting.adoc, modules/ROOT/pages/installing.adoc
=> [2.8] [PR 13] Add bin directory with makepdf

site.yml
Make a 2.7 site.yml
No Backport !
=> Make a 2.7 site.yml

bin/find-orphaned-files.sh, bin/instructions_makepdf.md, bin/makepdf
Changes to be aligned with changes made in docs
=> Alignment with docs

bin/find-orphaned-files.sh, bin/instructions_makepdf.md, bin/makepdf
=> [2.7] [PR 17] Alignment with docs

bin/find-orphaned-files.sh, bin/instructions_makepdf.md, bin/makepdf
=> [2.8] [PR 17] Alignment with docs

bin/makepdf
=> [2.7] [PR 20] Forgotten leftover of a makepdf option

bin/makepdf
=> [2.8] [PR 20] Forgotten leftover of a makepdf option

bin/find-orphaned-adoc-files, bin/find-orphaned-example-files
Find possible orphaned `.adoc` files
=> Find possible orphaned .adoc files

bin/find-orphaned-adoc-files, bin/find-orphaned-example-files
=> [2.7] [PR 24] Find possible orphaned .adoc files

bin/find-orphaned-adoc-files, bin/find-orphaned-example-files
=> [2.8] [PR 24] Find possible orphaned .adoc files

bin/find-orphaned-adoc-files
=> [2.7] [PR 27] Improved find adoc files catching false-positive incudes

bin/find-orphaned-adoc-files
=> [2.8] [PR 27] Improved find adoc files catching false-positive incudes

modules/ROOT/pages/installing.adoc
=> [2.8] [PR 30] Update supported platforms for clients 2.8.1

bin/find-orphaned-attachment-files, bin/find-orphaned-image-files
=> [2.8] [PR 32] Update to the find orphaned scripts

bin/find-orphaned-attachment-files, bin/find-orphaned-image-files
Backport of PR #(none)
accidentially direct merge to master
=> [2.8] [PR (none)] Fix orphaned script reason naming (text only)

bin/find-orphaned-attachment-files, bin/find-orphaned-image-files
Backport of PR #(none)
accidentially direct merge to master
=> [2.7] PR (none)] Fix orphaned script reason naming (text only)

.drone.star
Needs backport for 2.8 and 2.7
=> normalize starlark definition

.drone.star
=> [2.8] [PR 43] normalize starlark definition

.drone.star
=> [2.7] [PR 43] normalize starlark definition

bin/makepdf
=> [2.7] [PR 46] makepdf: add option for error output

bin/makepdf
=> [2.8] [PR 46] makepdf: add option for error output

README.md, docs/new-version-branch.md, docs/the-branching-workflow.md
=> [2.8] [PR 56] Fix Readme.md

README.md, docs/new-version-branch.md, docs/the-branching-workflow.md
=> [2.7] [PR 56] Fix Readme.md

package.json, yarn.lock
=> chore: update node dependencies

package.json, yarn.lock
=> [2.7] [PR 63] chore: update node dependencies

package.json, yarn.lock
=> [2.8] [PR 63] chore: update node dependencies

modules/ROOT/nav.adoc, modules/ROOT/pages/appendices/guitest.adoc
=> [2.8] [PR 62] Added docs for running GUI tests

modules/ROOT/pages/appendices/guitest.adoc
=> [2.8] [PR 68] change structure of squish setup

modules/ROOT/pages/appendices/building.adoc, site.yml
=> [2.8] [PR 70] Fix site.yml 2.8 and master

site.yml
=> [2.8] [PR 74] Remove unused site.yml variables

modules/ROOT/pages/appendices/guitest.adoc
This PR updates document on how to set up client and squish locally, and run GUI tests.
https://github.com/owncloud/client/issues/8841
=> [docs] updating docs for GUI tests

modules/ROOT/pages/appendices/guitest.adoc
=> [2.8] [PR 77] [docs] updating docs for GUI tests

modules/ROOT/nav.adoc, modules/ROOT/pages/filenames.adoc
=> [2.8] [PR 87] Filename Considerations

modules/ROOT/nav.adoc, modules/ROOT/pages/filenames.adoc
=> [2.7] [PR 87] Filename Considerations

modules/ROOT/pages/faq.adoc
=> [2.8] [PR 92] Alternate method for moving the sync folder

modules/ROOT/pages/faq.adoc
=> [2.7] [PR 92] Alternate method for moving the sync folder

modules/ROOT/pages/appendices/building.adoc
=> [2.8] [PR 100] Page alias for build instructions

modules/ROOT/pages/appendices/guitest.adoc
=> [2.9] [PR 104] Add note for password on BACKEND_HOST

modules/ROOT/pages/appendices/architecture.adoc, modules/ROOT/pages/appendices/troubleshooting.adoc
=> [2.9] [PR 106] add more page aliases for pages now in appendices folder

modules/ROOT/pages/appendices/architecture.adoc, modules/ROOT/pages/appendices/troubleshooting.adoc
=> [2.8] [PR 106] add more page aliases for pages now in appendices folder

modules/ROOT/pages/appendices/building.adoc, modules/ROOT/pages/appendices/troubleshooting.adoc, modules/ROOT/pages/faq.adoc, modules/ROOT/pages/installing.adoc, modules/ROOT/pages/navigating.adoc, modules/ROOT/pages/vfs.adoc
=> [2.8] [PR 109] Fix pdf image size

modules/ROOT/pages/appendices/building.adoc, modules/ROOT/pages/appendices/troubleshooting.adoc, modules/ROOT/pages/faq.adoc, modules/ROOT/pages/installing.adoc, modules/ROOT/pages/navigating.adoc, modules/ROOT/pages/vfs.adoc
=> [2.9] [PR 109] Fix pdf image size

bin/makepdf, bin/manual_config
=> [2.9] [PR 113] Update of the makepdf script and configuration to be inline with the other repos

bin/makepdf, bin/manual_config
=> [2.8] [PR 113] Update of the makepdf script and configuration to be inline with the other repos

modules/ROOT/nav.adoc, modules/ROOT/pages/appendices/release_notes.adoc
=> [2.9] [PR 120] Using release notes

modules/ROOT/nav.adoc, modules/ROOT/pages/appendices/release_notes.adoc
=> [2.8] [PR 120] Using release notes

modules/ROOT/pages/navigating.adoc
Adding the capability of marking singe, multiple or all lines (ctrl-a) and copy it to the clipboard.
Backport to 2.9
@michaelstingl fyi
=> Adding select capabilities in activities tabs

modules/ROOT/pages/navigating.adoc
=> [2.9] [PR 132] Adding select capabilities in activities tabs

bin/makepdf, lib/extensions/remote-include-processor.js, site.yml
=> [2.8] [PR 134] Prepare the repo to include external adoc files

bin/makepdf, lib/extensions/remote-include-processor.js, site.yml
=> [2.9] [PR 134] Prepare the repo to include external adoc files

modules/ROOT/pages/appendices/architecture.adoc, modules/ROOT/pages/navigating.adoc
=> [2.9] [PR 141] Part one fixing broken anchors (in- and inter-document references)

modules/ROOT/pages/appendices/architecture.adoc, modules/ROOT/pages/navigating.adoc
=> [2.8] [PR 141] Part one fixing broken anchors (in- and inter-document references)

modules/ROOT/pages/appendices/architecture.adoc
=> [2.9] [PR 144] Part three fixing broken anchors (in- and inter-document references)

modules/ROOT/pages/appendices/architecture.adoc
=> [2.8] [PR 144] Part three fixing broken anchors (in- and inter-document references)

modules/ROOT/pages/appendices/building.adoc, modules/ROOT/pages/installing.adoc
=> [2.8] [PR 147] Fix external broken links

modules/ROOT/pages/faq.adoc
=> [2.9] [PR 150] new faq item on quota

modules/ROOT/pages/faq.adoc
=> [2.8] [PR 150] new faq item on quota

modules/ROOT/pages/installing.adoc
After approval and merge, needs to be back ported to 2.9 branch
=> Update System Requirements for 2.9

modules/ROOT/pages/installing.adoc
Description added by @mmattel 
* Small installation documentation revision
* Adding AppImage
* Fix for #125 
Backport to 2.9 only
=> Add AppImage section to supported platforms

modules/ROOT/pages/installing.adoc
=> [2.9] [PR 155] Add AppImage section to supported platforms

docs/new-version-branch.md
=> [2.10] [PR 158] update new branch doc

docs/new-version-branch.md
=> [2.9] [PR 158] update new branch doc

docs/new-version-branch.md
=> [2.8] [PR 158] update new branch doc

modules/ROOT/pages/advanced_usage/environment_variables.adoc
=> [2.10] [PR 170] Document OWNCLOUD_OVERRIDE_SERVER_URL environment variable

modules/ROOT/pages/advanced_usage/environment_variables.adoc
=> [2.9] [PR 170] Document OWNCLOUD_OVERRIDE_SERVER_URL environment variable

bin/makepdf
=> [2.10] [PR 176] Fix for makepdf refs #169

bin/makepdf
=> [2.8] [PR 176] Fix for makepdf refs #169

README.md, package.json, yarn.lock
Referencing owncloud/docs#4616 (Add Antora Site Structure Description for Docs)
Plus harmonizing the package.json file.
Backport to 2.8, 2.9 and 2.10
=> Antora site structure

README.md, package.json, yarn.lock
=> [2.9] [PR187] Antora site structure

README.md, package.json, yarn.lock
=> [2.10] [PR 187] Antora site structure

README.md, package.json, yarn.lock
=> [2.8] [PR 187] Antora site structure

site.yml
=> [2.10] [PR 191] site.yml attribute fix

site.yml
=> [2.9] [PR 191] site.yml attribute fix

.drone.star, .prettierrc, generator/generate-site.js, package.json, yarn.lock
=> [2.10] [PR 194] Updates deployment files to be in sync with docs

.drone.star, .prettierrc, generator/generate-site.js, package.json, yarn.lock
=> [2.9] [PR 194] Updates deployment files to be in sync with docs

docs/new-version-branch.md
=> [2.10] [PR 200] update of the new version branch documentation

package.json
=> [2.10] [PR 203] adding a build command for staging

package.json
=> [2.9] [PR 203] adding a build command for staging

site.yml
=> [2.10] [PR 207] Harmonize site.yml to be inline with docs

site.yml
=> [2.9] [PR 207] Harmonize site.yml to be inline with docs

site.yml
=> [2.10] [PR 210] Add start_page in site.yml

site.yml
=> [2.9] [PR 210] Add start_page in site.yml

modules/ROOT/pages/installing.adoc
=> [2.10.0] System Requirements

modules/ROOT/pages/installing.adoc
=> [master] [PR 213] [2.10.0] System Requirements

modules/ROOT/pages/installing.adoc
=> [2.10] [PR 223] Update installing.adoc

modules/ROOT/pages/installing.adoc
=> [2.9] [PR 223] Update installing.adoc

modules/ROOT/pages/appendices/building.adoc, modules/ROOT/pages/appendices/guitest.adoc, modules/ROOT/pages/installing.adoc
Using the correct source language in examples
Backport to 2.10 and 2.9
=> Use correct source language

modules/ROOT/pages/appendices/building.adoc, modules/ROOT/pages/appendices/guitest.adoc, modules/ROOT/pages/installing.adoc
=> [2.10] [PR 226] Use correct source language

modules/ROOT/pages/appendices/building.adoc, modules/ROOT/pages/appendices/guitest.adoc, modules/ROOT/pages/installing.adoc
=> [2.9] [PR 226] Use correct source language

modules/ROOT/pages/installing.adoc
and remove trailing dots on some msiexec commands
=>  Update 2.10.1 system requirements

docs/new-version-branch.md
=> [2.10] [PR 233] branching text fix

docs/new-version-branch.md
=> [2.9] [PR 233] branching text fix

README.md, bin/find-orphaned-adoc-files, bin/instructions_makepdf.md, bin/makepdf, bin/manual_config_pdf, bin/yamlparse.sh, docs/new-version-branch.md, modules/ROOT/pages/advanced_usage/command_line_client.adoc, modules/ROOT/pages/advanced_usage/configuration_file.adoc, modules/ROOT/pages/appendices/architecture.adoc, modules/ROOT/pages/appendices/building.adoc, modules/ROOT/pages/appendices/guitest.adoc, modules/ROOT/pages/appendices/troubleshooting.adoc, modules/ROOT/pages/automatic_updater.adoc, modules/ROOT/pages/conflicts.adoc, modules/ROOT/pages/faq.adoc, modules/ROOT/pages/filenames.adoc, modules/ROOT/pages/installing.adoc, modules/ROOT/pages/navigating.adoc, modules/ROOT/pages/removing.adoc, resources/themes/custom-theme.yml
I noticed the recently-added typo "Show in Exporer", so I did a grammar/typo check through this repo. These are the things that my IDE found that I think need changing.
=> Various minor typo and grammar changes

README.md, bin/find-orphaned-adoc-files, bin/instructions_makepdf.md, bin/makepdf, bin/manual_config_pdf, bin/yamlparse.sh, docs/new-version-branch.md, modules/ROOT/pages/advanced_usage/command_line_client.adoc, modules/ROOT/pages/advanced_usage/configuration_file.adoc, modules/ROOT/pages/appendices/architecture.adoc, modules/ROOT/pages/appendices/building.adoc, modules/ROOT/pages/appendices/guitest.adoc, modules/ROOT/pages/appendices/troubleshooting.adoc, modules/ROOT/pages/automatic_updater.adoc, modules/ROOT/pages/conflicts.adoc, modules/ROOT/pages/faq.adoc, modules/ROOT/pages/filenames.adoc, modules/ROOT/pages/installing.adoc, modules/ROOT/pages/navigating.adoc, modules/ROOT/pages/removing.adoc, resources/themes/custom-theme.yml
=> [2.10] [PR 238] Various minor typo and grammar changes

README.md, bin/find-orphaned-adoc-files, bin/instructions_makepdf.md, bin/makepdf, bin/manual_config_pdf, bin/yamlparse.sh, docs/new-version-branch.md, modules/ROOT/pages/advanced_usage/command_line_client.adoc, modules/ROOT/pages/advanced_usage/configuration_file.adoc, modules/ROOT/pages/appendices/architecture.adoc, modules/ROOT/pages/appendices/building.adoc, modules/ROOT/pages/appendices/guitest.adoc, modules/ROOT/pages/appendices/troubleshooting.adoc, modules/ROOT/pages/automatic_updater.adoc, modules/ROOT/pages/conflicts.adoc, modules/ROOT/pages/faq.adoc, modules/ROOT/pages/filenames.adoc, modules/ROOT/pages/installing.adoc, modules/ROOT/pages/navigating.adoc, modules/ROOT/pages/removing.adoc, resources/themes/custom-theme.yml
=> [2.9] [PR 238] Various minor typo and grammar changes

modules/ROOT/pages/navigating.adoc
=> [2.11] [PR 275] Note about what is a hidden file

modules/ROOT/pages/navigating.adoc
=> [2.10] [PR 275] Note about what is a hidden file

modules/ROOT/pages/appendices/guitest.adoc
=> [2.11] [PR 280] Update GUI testing docs

modules/ROOT/pages/installing.adoc
=> [2.10] [PR 278] Add MSI logging command

modules/ROOT/pages/installing.adoc
=> [2.11] [PR 278] Add MSI logging command

modules/ROOT/pages/faq.adoc
This fixes issue #273 
Backport to 2.10 and 2.11 necessary.
=> Explanation for different file size displays added to FAQ

modules/ROOT/pages/installing.adoc
=> [2.11] [PR 294] Update the installation description with regards to config files

modules/ROOT/pages/installing.adoc
=> [3.0] [PR 294] Update the installation description with regards to config files

modules/ROOT/pages/installing.adoc
=> [master] [PR 298] Remove macOS legacy builds

modules/ROOT/pages/installing.adoc
=> [2.11] [PR 298] Remove macOS legacy builds

modules/ROOT/pages/navigating.adoc
=> [3.0] [PR 302] Adding info about client restart after ignored list changes

modules/ROOT/pages/navigating.adoc
=> [2.11] [PR 302] Adding info about client restart after ignored list changes

modules/ROOT/pages/appendices/building.adoc
=> [3.0] [PR 307] Fix a broken internal link

modules/ROOT/pages/appendices/building.adoc
=> [2.11] [PR 307] Fix a broken internal link

modules/ROOT/pages/installing.adoc
=> [3.0] [PR 310] Add fixes to the appimage description

modules/ROOT/pages/installing.adoc
Fixes: #267 ([AppImage] HowTo install file browser extension packages manually)
Describe how to install File Browser Extension Packages.
Backport to 3.0 and 2.11
=> Install File Browser Extension Packages

modules/ROOT/pages/installing.adoc
=> [3.0] [PR 303] Install File Browser Extension Packages

modules/ROOT/pages/installing.adoc
=> [2.11] [PR 303] Install File Browser Extension Packages

modules/ROOT/pages/appendices/guitest.adoc
=> [3.0] [PR 329] update testing doc for oCIS

modules/ROOT/pages/advanced_usage/command_line_client.adoc, modules/ROOT/partials/nav.adoc
=> [3.0] [PR 332] Fixe the command line page

modules/ROOT/pages/appendices/troubleshooting.adoc, modules/ROOT/pages/faq.adoc, modules/ROOT/pages/installing.adoc, modules/ROOT/pages/navigating.adoc, modules/ROOT/pages/vfs.adoc
=> [3.0] [PR 339] Fix image width

modules/ROOT/pages/appendices/troubleshooting.adoc, modules/ROOT/pages/faq.adoc, modules/ROOT/pages/installing.adoc, modules/ROOT/pages/navigating.adoc, modules/ROOT/pages/vfs.adoc
=> [2.11] [PR 339] Fix image width

modules/ROOT/pages/faq.adoc
=> [3.0] [PR 342] Explain cleanup of Not Synced messages

modules/ROOT/pages/faq.adoc
=> [2.11] [PR 342] Explain cleanup of Not Synced messages

modules/ROOT/pages/faq.adoc, modules/ROOT/pages/installing.adoc, modules/ROOT/pages/vfs.adoc
=> [master] [317] [Windows] Clarify requirement for native WinVFS

modules/ROOT/pages/faq.adoc, modules/ROOT/pages/installing.adoc, modules/ROOT/pages/vfs.adoc
=> [2.11] [PR 317] [Windows] Clarify requirement for native WinVFS

docs/new-version-branch.md
* We have version starting with 3.x
* Some text improvements
* Updating recipients
=> Update the text for creating a new branch

modules/ROOT/pages/installing.adoc
=> [3.0] [PR 351] How to fix signature verification errors

modules/ROOT/pages/installing.adoc
=> [3.1] [PR 351] How to fix signature verification errors

modules/ROOT/pages/advanced_usage/command_line_client.adoc
=> [3.0] [PR 363] owncloudcmd new WebDAV endpoint

modules/ROOT/pages/installing.adoc
@fmoc @HanaGemela that's my plan for the customer announcement for the branded 3.2 release 
(based on https://cloud.owncloud.com/index.php/f/5870330)
No Backport
=> System requirements updated for 3.2 release

modules/ROOT/pages/installing.adoc
=> [3.2] [PR 375] Update AppImage-specific insructions for upcoming 3.2 release

modules/ROOT/pages/installing.adoc
=> [master] [PR 380] Ubuntu 21.10 has become end of life

modules/ROOT/pages/advanced_usage/environment_variables.adoc
=> [master] [PR 382] Bring back lost OCC_UPDATE_URL

modules/ROOT/pages/appendices/troubleshooting.adoc
Fixes: #391 (Log to console, remove workaround Write-Host)
* remove Write-Host
* add more toc levels to show
* improve some renderings
Backport to 3.2 and 3.1
=> Remove Write-Host

modules/ROOT/pages/installing.adoc
=> [4.0] [PR 412] System requirements updated for 4.0 release

modules/ROOT/pages/installing.adoc
=> [4.1] [PR 441] System requirements updated for 4.1 release

modules/ROOT/pages/installing.adoc
=> [4.1] [PR 444] Fix system requirements for 4.1 release

modules/ROOT/pages/appendices/building.adoc
=> [4.0] [PR 448] Fix broken link

modules/ROOT/pages/advanced_usage/command_line_client.adoc
Some small rendering fixes to improve reading quality.
=> Small render fixes

modules/ROOT/pages/using.adoc
Fixes: #327 (Pattern in ignored files is applied to folders as well)
As the title says...
=> Rules for ignored files are also applied to folders

modules/ROOT/pages/using.adoc
=> [4.0] [PR 460] Rules for ignored files are also applied to folders

modules/ROOT/pages/using.adoc
=> [4.1] [PR 460] Rules for ignored files are also applied to folders

modules/ROOT/pages/advanced_usage/command_line_client.adoc
=> [4.1] [PR 462] Small render fixes

modules/ROOT/pages/advanced_usage/command_line_client.adoc
=> [4.0] [PR 462] Small render fixes

modules/ROOT/pages/advanced_usage/configuration_file.adoc, modules/ROOT/pages/faq.adoc
=> [4.0] [PR 469] Clarify terms, query intervals and impacts

modules/ROOT/pages/appendices/building.adoc, modules/ROOT/pages/appendices/troubleshooting.adoc, modules/ROOT/pages/automatic_updater.adoc
https://en.wikipedia.org/wiki/MacOS
=> Mac OS X is now macOS

modules/ROOT/pages/appendices/building.adoc, modules/ROOT/pages/appendices/troubleshooting.adoc, modules/ROOT/pages/automatic_updater.adoc
=> [4.0] [PR 479] Mac OS X is now macOS

modules/ROOT/pages/appendices/building.adoc, modules/ROOT/pages/appendices/troubleshooting.adoc, modules/ROOT/pages/automatic_updater.adoc
=> [4.1] [PR 479] Mac OS X is now macOS

modules/ROOT/pages/vfs.adoc
=> [4.0] [PR 482] Using attrib.exe to Manage States

modules/ROOT/pages/vfs.adoc
=> [4.1] [PR 482] Using attrib.exe to Manage States

modules/ROOT/pages/using.adoc, site.yml
=> [4.1] [PR 497] Update site.yml and add a small fix

modules/ROOT/pages/using.adoc, site.yml
=> [4.0] [PR 497] Update site.yml and add a small fix

modules/ROOT/pages/faq.adoc
@EParzefall @mmattel please make this nice. Thanks!
=> FAQ: Workaround for syncing local changes from mounted network volume

modules/ROOT/pages/faq.adoc
=> [4.0] [PR 486] FAQ: Workaround for syncing local changes from mounted network volume

modules/ROOT/pages/faq.adoc
=> [4.1] [PR 486] FAQ: Workaround for syncing local changes from mounted network volume

modules/ROOT/pages/installing.adoc
=> [master] [PR 502] Add Apple ARM64 to System Requirements

modules/ROOT/pages/web_app.adoc
=> [4.1] [PR 506] Adapt Office Web Apps page

modules/ROOT/pages/web_app.adoc
=> [4.2] [PR 506] Adapt Office Web Apps page

modules/ROOT/pages/appendices/troubleshooting.adoc
=> [4.2] [PR 509] Explain HTTP logging basic in troubleshooting.adoc

modules/ROOT/pages/appendices/troubleshooting.adoc
=> [4.1] [PR 509] Explain HTTP logging basic in troubleshooting.adoc

modules/ROOT/pages/installing.adoc
@TheOneRing @HanaGemela please check
(based on https://cloud.owncloud.com/index.php/f/5870330)
Backport to 5.0 only
=> System requirements updated for 5.0 release

modules/ROOT/pages/installing.adoc
=> [4.2] [PR 520] Fix missing gnome shell extensions appindicator for Redhat distros

modules/ROOT/pages/installing.adoc
=> [5.0] [PR 520] Fix missing gnome shell extensions appindicator for Redhat distros

modules/ROOT/pages/appendices/guitest.adoc
Updated note about supported QT version and changed sub-heading.
=> Update the GUI testing page

modules/ROOT/pages/appendices/guitest.adoc
=> [5.0] [PR 527] Update the GUI testing page

modules/ROOT/pages/installing.adoc
Change client version number in `installing.adoc`
Backport to 5.1 only
=> Update installing.adoc with the final 5.1.1 build number

modules/ROOT/pages/installing.adoc
=> [5.1] [PR 533] Update installing.adoc with the final 5.1.1 build number

.gitignore, README.md, bin/prepare_site_yml, docs/new-version-branch.md
References: https://github.com/owncloud/docs/pull/4903
This PR is a first step describing an setting up a dev env.
Most likely more to come.
Backport to 5.1 and 5.0
=> Update readme and prepare dev env

.gitignore, README.md, bin/prepare_site_yml, docs/new-version-branch.md
=> [5.1]  [PR 543] Update readme and prepare dev env

.gitignore, README.md, bin/prepare_site_yml, docs/new-version-branch.md
=> [5.0] [PR 543] Update readme and prepare dev env

package.json
=> [5.1] [PR 546] Update package.json

package.json
=> [5.0] [PR 546] Update package.json

modules/ROOT/pages/installing.adoc
Win:
https://download.owncloud.com/desktop/ownCloud/stable/5.2.0.12726/win/
AppImage:
https://download.owncloud.com/desktop/ownCloud/stable/5.2.0.12726/linux-appimage/
---
Backport to 5.2 only
=> 5.2 install string changes

modules/ROOT/pages/installing.adoc
This helps users and admins to choose the best version for their requirements.
---
Can be back-ported.
=> Explain GPO in installing.adoc

modules/ROOT/pages/installing.adoc
=> [5.1] [PR 555] Explain GPO in installing.adoc

modules/ROOT/pages/appendices/guitest.adoc
This PR adds information for running GUI tests in Windows platform.
Part of: https://github.com/owncloud/client/issues/9833
=> Docs for running GUI test in Windows

modules/ROOT/pages/installing.adoc
=> [5.2] [PR 555] Explain GPO in installing.adoc

modules/ROOT/pages/appendices/guitest.adoc
=> [5.1] [PR 554] Docs for running GUI test in Windows

docs/new-version-branch.md
=> [5.2] [PR 571] Just a small internal link fix

es-docker-compose.yml
=> [5.2] [PR 574] Add ES example yml for ease of testing

es-docker-compose.yml
=> [5.1] [PR 574] Add ES example yml for ease of testing

ext-antora/generate-index.js
Fix a edge case for search index generation.
Backport to 5.1 and 5.2
=> Fix a edge case for search index generation.

ext-antora/generate-index.js
=> [5.2] [PR 577] Fix a edge case for search index generation.

ext-antora/generate-index.js
=> [5.1] [PR 577] Fix a edge case for search index generation.

docs/new-version-branch.md, ext-antora/generate-index.js
Script update for consistency + small fixes.
Backport to 5.2 and 5.1
=> Es index update

docs/new-version-branch.md, ext-antora/generate-index.js
=> [5.2] [PR 580] Es index update

docs/new-version-branch.md, ext-antora/generate-index.js
=> [5.1] [PR 580] Es index update

modules/ROOT/pages/appendices/release_notes.adoc
Added releasenotes
- Enhanced Functionality
- Notable Bugfixes
- Requirements
- Newly supported platforms
- Deprecated
- Deprecation Announcements
- Branding
=> Releasenotes 5.2.1

modules/ROOT/pages/appendices/release_notes.adoc
=> [master] [PR 586] Releasenotes 5.2.1

modules/ROOT/pages/advanced_usage/configuration_file.adoc, modules/ROOT/pages/advanced_usage/index.adoc, modules/ROOT/pages/advanced_usage/low_disk_space.adoc, modules/ROOT/pages/appendices/architecture.adoc, modules/ROOT/pages/appendices/index.adoc, modules/ROOT/pages/appendices/troubleshooting.adoc, modules/ROOT/pages/automatic_updater.adoc, modules/ROOT/pages/faq.adoc, modules/ROOT/pages/installing.adoc, modules/ROOT/pages/using.adoc, modules/ROOT/pages/vfs.adoc, modules/ROOT/pages/web_app.adoc, modules/ROOT/partials/nav.adoc
This PR fixes the following:
* Nearly all images needed a sizing fix to improve rendering
* Image positioning
* Table centering where necessary
* Table fixes
* Removing unneeded index.adoc files from the navigation
No content changes.
Backport to 5.2
=> Image and rendering fixes

modules/ROOT/pages/advanced_usage/configuration_file.adoc, modules/ROOT/pages/advanced_usage/index.adoc, modules/ROOT/pages/advanced_usage/low_disk_space.adoc, modules/ROOT/pages/appendices/architecture.adoc, modules/ROOT/pages/appendices/index.adoc, modules/ROOT/pages/appendices/troubleshooting.adoc, modules/ROOT/pages/automatic_updater.adoc, modules/ROOT/pages/faq.adoc, modules/ROOT/pages/installing.adoc, modules/ROOT/pages/using.adoc, modules/ROOT/pages/vfs.adoc, modules/ROOT/pages/web_app.adoc, modules/ROOT/partials/nav.adoc
=> [5.2] [PR 591] Image and rendering fixes

modules/ROOT/pages/installing.adoc
Updated the client version to the latest released version.
=> [5.3] [PR 601] docs: update client version in the installation doc

package.json, yarn.lock
=> [5.3] [PR 611] Antora package.json refactoring

package.json, yarn.lock
=> [5.2] [PR 611] Antora package.json refactoring

modules/ROOT/pages/installing.adoc
refs https://github.com/owncloud/client/issues/11960
=> fix: adjust system requirements for desktop client 6.0.0

ext-antora/comp-version.js
=> [5.3] [PR 624] Update antora extension to print component, versions and files

ext-antora/comp-version.js
=> [5.2] [PR 624] Update antora extension to print component, versions ans files

modules/ROOT/pages/installing.adoc
=> [5.3] [PR 630] Updated install docs with the final version and build number

ext-antora/comp-version.js
=> [5.3] [PR 632] Update the component-version counting extension

ext-antora/comp-version.js
=> [5.2] [PR 632] Update the component-version counting extension

modules/ROOT/pages/automatic_updater.adoc
=> [5.3] [PR 635] Remove remaining hardcoded links to branding

modules/ROOT/pages/automatic_updater.adoc
=> [5.2] [PR 635] Remove remaining hardcoded links to branding

docs/new-version-branch.md, docs/the-branching-workflow.md
=> [5.3] [PR 638] Update the versioning process

docs/new-version-branch.md, docs/the-branching-workflow.md
=> [5.2] [PR 638] Update the versioning process

ext-antora/find-orphaned-files.js
Update the `Find Orphaned Files Extension` Antora extension
=> Update or add find orphaned antora extension

modules/ROOT/pages/installing.adoc
=> [6.0] [PR 657] Fixing an italic formatting issue
