- bin/makepdf
Option `-l` no longer present and removed (in sync with docs)
Backports to 2.7 and 2.8
> Forgotten leftover of a makepdf option

- bin/find-orphaned-adoc-files
Updates the find-orphand-adoc files script to catch false positives when using the `include::` directive.
> Improved find adoc files catching false-positive incudes

- modules/ROOT/pages/installing.adoc
References: https://github.com/owncloud/client/pull/8662
Backporting to 2.8
> Update supported platforms for clients 2.8.1

- bin/makepdf
Add an option to set the log-level to ERROR for printing errors (default would be FATAL only)
@xoxys fyi
> makepdf: add option for error output

- README.md
- docs/new-version-branch.md
- docs/the-branching-workflow.md
Fixes readme.md to reflect the current build changes, notes and how to setup new version branches propely.
Should be backported to 2.7 and 2.8
When this PR gets merged, we can use this repo as template for the other clients.
@xoxys you may be interestend in the new version branch setup giude: `docs/new-version-branch.md`
> Fix Readme.md

- modules/ROOT/nav.adoc
- modules/ROOT/pages/appendices/guitest.adoc
This PR adds document on how to set up client and squish locally, and run GUI tests.
https://github.com/owncloud/client/issues/8705
> Added docs for running GUI tests

- modules/ROOT/pages/appendices/guitest.adoc
After https://github.com/owncloud/docs-client-desktop/pull/62 has been merged there are some minor changes that needed to be done in the documentation for `GUI Testing the Desktop Client`. Following are the changes made:
-  Move `Install Squish` and `Configure Squish` from `Prerequisites` to inside of `Prepare Tests` -> ` Using Squish IDE`
- remove `Installing Squish Using an Executable File` heading
-  python changer script did not have an URL but `pythonchanger-url[Download]`
- replace `license key` with `license/url of the license server` to make it more clearer.
> change structure of squish setup

- modules/ROOT/pages/appendices/building.adoc
- site.yml
We have "confusing" variable names as they are used in many repos and if there are errors raising during compilation, we do not know which doc is the origin of the error.
No backport, master (and 2.8) have their own PR
> Fix site.yml 2.7

- modules/ROOT/pages/appendices/building.adoc
- site.yml
We have "confusing" variable names as they are used in many repos and if there are errors raising during compilation, we do not know which doc is the origin of the error.
Backport to 2.8 only, 2.7 will get a own PR for this.
> Fix site.yml 2.8 and master

- site.yml
Remove unused site.yml variables
Backport to 2.8
Note that 2.7 has its own PR for this
> Remove unused site.yml variables

- site.yml
Remove unused site.yml variables for 2.7
No backport, as master and 2.8 have their own PR
> Remove unused site.yml variables in 2.7

- modules/ROOT/pages/appendices/building.adoc
on ubuntu 20.04 pyhton-sqhinx no longer exists.
> generic build instructions should use python3-sphinx

- modules/ROOT/pages/appendices/building.adoc
> [2.8] [PR 76] generic build instructions should use python3-sphinx

- modules/ROOT/nav.adoc
- modules/ROOT/pages/filenames.adoc
References: #52 (Documentation about Syncing of "problematic" filenames)
References: https://github.com/owncloud/core/issues/29759 ([Feature Request] Check if file names restrictions apply for a given mount (filesystem))
Add a description about problematic filenames and how to deal with.
Backporting to 2.8 and 2.7
> Filename Considerations

- modules/ROOT/pages/faq.adoc
It is also possible to move manually (a) as a full re-sync (b) may not always be desirable.
the instructions in a) are intentionally terse, so that novice users would rather choose b).
> Alternate method for moving the sync folder

- .drone.star
HTML upload has to be done by the build repo https://github.com/owncloud/docs for all clients, not in the client repos itself.
> fix: remove html upload

- modules/ROOT/pages/appendices/building.adoc
potential solution for https://github.com/owncloud/client/issues/8990
I tried it locally:
```
% curl http://localhost:8080/desktop/next/building.html
<!DOCTYPE html>
<meta charset="utf-8">
<link rel="canonical" href="https://doc.owncloud.com/desktop/next/appendices/building.html">
<script>location="appendices/building.html"</script>
<meta http-equiv="refresh" content="0; url=appendices/building.html">
<meta name="robots" content="noindex">
<title>Redirect Notice</title>
<h1>Redirect Notice</h1>
<p>The page you requested has been relocated to <a href="appendices/building.html">https://doc.owncloud.com/desktop/next/appendices/building.html</a>.</p>
```
> Page alias for build instructions

- .drone.star
- site.yml
The 2.9 branch has been created based on master, adopted and pushed.
These are the changes in master so that the actual branch is set to 2.9
Post merging:
* the 2.7 branch will be renamed and archived according the process described in docs.
* in docs, the desktop releases + pdf links are checked/adopted to the branches available
NO BACKPORTING !!
> Changes necessary for the 2.9 branch

- modules/ROOT/pages/appendices/guitest.adoc
Add the hint for account settings on BACKEND_HOST, see https://github.com/owncloud/client/issues/8841#issuecomment-889034155
> Add note for password on BACKEND_HOST

- modules/ROOT/pages/appendices/architecture.adoc
- modules/ROOT/pages/appendices/troubleshooting.adoc
During migration in separate repo, some pages were moved in `appendices` subfolder. This broke some already published links. After moving of pages, `:page-aliases:` feature should be used. (related: https://github.com/owncloud/docs-client-desktop/pull/100)
> add more page aliases for pages now in appendices folder

- modules/ROOT/pages/appendices/building.adoc
- modules/ROOT/pages/appendices/troubleshooting.adoc
- modules/ROOT/pages/faq.adoc
- modules/ROOT/pages/installing.adoc
- modules/ROOT/pages/navigating.adoc
- modules/ROOT/pages/vfs.adoc
This PR fixes the image sizes for the pdf files, they were mostly much too small.
Now they are sized correctly.
A manual pdf creation and visual test shows them ok now.
Also fixed a missing introduction section header
Backporting to 2.9 and 2.8
> Fix pdf image size

- bin/makepdf
- bin/manual_config
Just a small update, it handles the case that the first letter is not capital (see iOS)
Backport to 2.9 and 2.8
> Update of the makepdf script and configuration to be inline with the other repos

- modules/ROOT/pages/index.adoc
The client entry page should not feature client version 2.2.1 or server versions 8.1 both are horribly outdated.
Do we want to speak about supported versions here?
backport to 2.9 would be cool!
> remove outdated version numbers

- bin/makepdf
- lib/extensions/remote-include-processor.js
- site.yml
This PR prepares the repo to include .adoc files from an URI.
For details see the comments in script: lib/extensions/remote-include-processor.js
Referencing https://github.com/owncloud/docs-client-ios-app/pull/18 (Prepare the repo to include external adoc files)
That is the first repo where this is needed, harmonizing the setup.
**Tests**
Tests have been made in the referenced PR - all works as expected.
The nice thing having this, we can now include any .adoc file automatically generated by a script from an external URI like another github repo, without manually maintaining static content.
**NOTE**
Any external created content, especially if created dynamically, MUST be checked carefully for building properly!
Backport to 2.9 and 2.8
> Prepare the repo to include external adoc files

- modules/ROOT/pages/appendices/architecture.adoc
- modules/ROOT/pages/navigating.adoc
This is part one fixing broken anchors...
Backport to 2.9 and 2.8
> Part one fixing broken anchors (in- and inter-document references)

- modules/ROOT/pages/appendices/architecture.adoc
This is part three fixing broken anchors...
(fixing a upper/lower case typo)
Backport to 2.9 and 2.8
Note, part two was accidentially direct committed against 2.8 instead via a branch and by pushing, it got merged. See the following reference for changes (only one line) https://github.com/owncloud/docs-client-desktop/commit/00989eae5b7e8a9c2b8bd0f4699609afe4587156
> Part three fixing broken anchors (in- and inter-document references)

- modules/ROOT/pages/appendices/building.adoc
- modules/ROOT/pages/installing.adoc
This PR fixes broken links to external documents.
Backport to 2.9 and 2.8 necessary.
> Fix external broken links

- modules/ROOT/pages/faq.adoc
Explanation why different quota usage is displayed in the web UI and on the desktop client.
This fixes issue #138 
Backports to 2.9 and 2.8 needed
> new faq item on quota

- docs/new-version-branch.md
This PR updates the new branch documentation, fixes a typo and adds a copy/paste text for new branches (similar as in docs).
Backport to 2.10, 2.9 and 2.8 (if not already archived)
> update new branch doc

- modules/ROOT/pages/advanced_usage/environment_variables.adoc
Implemented here: https://github.com/owncloud/client/pull/8772
@TheOneRing correct?
Backport to 2.9, not earlier!
> Document OWNCLOUD_OVERRIDE_SERVER_URL environment variable

- bin/makepdf
Fixing a missed change in an attribute in makepdf.
References #169 (Fix the family directory structure)
Backport to 2.10, 2.9 and 2.8
> Fix for makepdf refs #169

- .drone.star
- site.yml
These are the changes necessary to finalize the creation of the 2.10 branch.
The 2.10 branch is already pushed and prepared and is included in the branch protection rules.
When 2.10 (Desktop) is finally out, the 2.8 branch can be archived,
see step 4 in https://github.com/owncloud/docs-client-desktop/blob/master/docs/new-version-branch.md
Note, that the 2.10 branch in this repo is already created, but the `latest` pointer on the web
will be set to it automatically when the tag in Desktop is set. This means, that in the docs homepage,
`latest` will point to 2.9 until the tag in Desktop is set accordingly. When merging this PR,
2.8 will be dropped from the web but is available via pdf as usual.
Note, this PR must be merged before the 2.10 tag in Desktop is set to avoid a 404 for `latest`. …
> Changes necessary for 2.10

- .drone.star
> [2.10] [PR 197] chore: replace s3 server in drone config by secret

- .drone.star
> [2.9] [PR 197] chore: replace s3 server in drone config by secret

- .drone.star
- site.yml
These are the changes necessary to finalize the creation of the 2.11 branch.
The 2.11 branch is already pushed and prepared and is included in the branch protection rules.
When 2.11 (Desktop) is finally out, the 2.9 branch can be archived,
see step 4 in https://github.com/owncloud/docs-client-desktop/blob/master/docs/new-version-branch.md
Note, that the 2.11 branch in this repo is already created, but the `latest` pointer on the web
will be set to it automatically when the tag in Desktop is set. This means, that in the docs homepage,
`latest` will point to 2.10 until the tag in Desktop is set accordingly. When merging this PR,
2.9 will be dropped from the web but is available via pdf as usual.
Note, this PR must be merged before the 2.11 tag in Desktop is set to avoid a 404 for `latest`. …
> Changes necessary for 2.11

- modules/ROOT/pages/installing.adoc
Fixes: https://github.com/owncloud/docs-client-desktop/issues/250 (Update AppImage related documentation before 2.11 release)
Some small changes with regards to AppImage.
Backport to 2.11 only
@fmoc fyi
> Update Appimage which is now based on CentOS 7

- modules/ROOT/pages/installing.adoc
> [2.11] [PR 251] Update Appimage which is now based on CentOS 7

- modules/ROOT/pages/navigating.adoc
Related client PR:
https://github.com/owncloud/client/pull/10112
@mmattel only merge to 3.0+  --> NO backport
> Clarify changed bandwidth behaviour in 3.0+

- modules/ROOT/pages/appendices/guitest.adoc
In this PR, I have updated the dead link to the python changer file, updated correct path for the config file and added some useful Notes like squish-QT version required for desktop client >=2.11
Closes https://github.com/owncloud/client/issues/9247
> Update GUI testing docs

- .drone.star
- site.yml
These are the changes necessary to finalize the creation of the 3.0 branch.
The 3.0 branch is already pushed and prepared and is included in the branch protection rules.
When 3.0 (Desktop) is finally out, the 2.10 branch can be archived,
see step 4 in https://github.com/owncloud/docs-client-desktop/blob/master/docs/new-version-branch.md
Note, that the 3.0 branch in this repo is already created, but the `latest` pointer on the web
will be set to it automatically when the tag in Desktop is set. This means, that in the docs homepage,
`latest` will point to 2.11 until the tag in Desktop is set accordingly. When merging this PR,
2.10 will be dropped from the web but is available via pdf as usual.
Note, this PR must be merged before the 3.0 tag in Desktop is set to avoid a 404 for `latest`. …
> Changes necessary for 3.0

- modules/ROOT/pages/installing.adoc
Fixes: #293 (How to achieve clean installation with AppImage)
* Adding info about the configuration file when installing
* Change native M1 support to Q2 2024 (info from Holger)
* Improve the general installation description for Win & macOS
* Harmonize macOS naming
Backport to 3.0 and 2.11
> Update the installation description with regards to config files

- modules/ROOT/pages/navigating.adoc
Sync client restart is needed for changes to the ignored files list to take place. This is currently not documented and can be confusing for the users as this is not consistent to what described in the client itself.
@michaelstingl maybe we should also adjust the text in the client.
Backport to 3.0 and 2.11
> Adding info about client restart after ignored list changes

- modules/ROOT/pages/appendices/building.adoc
As the title says, found via htmltest.
Backport to 3.0 and 2.11
> Fix a broken internal link

- modules/ROOT/pages/installing.adoc
Fixes: #306 Update AppImage limitations list
New limitations for the AppImage 3.0 version
Backport to 3.0 only
> Add fixes to the appimage description

- modules/ROOT/pages/appendices/guitest.adoc
Updated doc about running tests with oCIS server
Closes https://github.com/owncloud/docs-client-desktop/issues/328
Served locally:
> update testing doc for oCIS

- modules/ROOT/pages/advanced_usage/command_line_client.adoc
- modules/ROOT/partials/nav.adoc
References: #315 (Fix owncloudcmd)
* accidentially the table was not closed properly
* though removing a dupe page and setting an alias, the page was still available in the navigation
Backport to 3.0
> Fixe the command line page

- modules/ROOT/pages/appendices/guitest.adoc
Referencing #329 (update testing doc for oCIS)
The referenced PR removed an attribute making the build fail because no checking was made before merging 👎 
This PR fixes the missing attribute but needs checking if the changes are ok in the context.
Backport to 3.0
> Followup fix for guitest

- modules/ROOT/pages/appendices/troubleshooting.adoc
- modules/ROOT/pages/faq.adoc
- modules/ROOT/pages/installing.adoc
- modules/ROOT/pages/navigating.adoc
- modules/ROOT/pages/vfs.adoc
From a legacy, it was formerly allowed to use a percent value for html when defining the width. There is a warning from Antora (also some time ago) not to use this anymore as the rendered result will not return the expected view. This PR fixes this for this repo, all images now render correctly as required.
A local build shows that all images are ok now.
In addition, some minor things have been fixed too.
Backport to 3.0 and 2.11 (for the latter we need to check if it renders correctly and if there are conflicts)
> Fix image width

- modules/ROOT/pages/faq.adoc
Fixes: #324 ([FAQ] Explain cleanup of error messages)
* Add a text that explains how messages appear and disappear in the `Not Synced` tab.
* Shortended a headline for better readability
* Add the description attribute
Backpor to 3.0 and 2.11
> Explain cleanup of Not Synced messages

- modules/ROOT/pages/faq.adoc
- modules/ROOT/pages/installing.adoc
- modules/ROOT/pages/vfs.adoc
- package.json
- yarn.lock
According to my knowledge, native WinVFS works on all Win versions > 1709 (Win 10, 11, Win server 2019 + 2022)
@TheOneRing works for you?
Backport to master and 2.9
> [Windows] Clarify requirement for native WinVFS

- .drone.star
- site.yml
These are the changes necessary to finalize the creation of the 3.1 branch.
The 3.1 branch is already pushed and prepared and is included in the branch protection rules.
When 3.1 (Desktop) is finally out, the 2.11 branch can be archived, see step 4 in https://github.com/owncloud/docs-client-desktop/blob/master/docs/new-version-branch.md
Note, that the 3.1 branch in this repo is already created, but the `latest` pointer on the web will be set to it automatically when the tag in Desktop is set. This means, that in the docs homepage, `latest` will point to 3.0 until the tag in Desktop is set accordingly. When merging this PR, 2.11 will be dropped from the web but is available via pdf as usual.
Note, this PR must be merged before the 3.1 tag in Desktop is set to avoid a 404 for `latest`.
Note …
> Changes necessary for 3.1

- modules/ROOT/pages/installing.adoc
I recently ran into the issue that when running `sudo apt update` that the command returns signature verification errors. This PR adds a note for Debian based systems how to update the signatures.
Backport to 3.1 and 3.0
> How to fix signature verification errors

- modules/ROOT/pages/appendices/guitest.adoc
Fixes: #355
Added browser installation command 
Backport to 3.1 and 3.0
> update desktop app testing docs for ocis

- modules/ROOT/pages/appendices/guitest.adoc
> [3.1] [PR 356] update desktop app testing docs for ocis

- modules/ROOT/pages/appendices/guitest.adoc
> [3.0] [PR 356] update desktop app testing docs for ocis

- .drone.star
- site.yml
These are the changes necessary to finalize the creation of the 3.2 branch.
The 3.2 branch is already pushed and prepared and is included in the branch protection rules.
When 3.2 (Desktop) is finally out, the 3.0 branch can be archived, see step 4 in https://github.com/owncloud/docs-client-desktop/blob/master/docs/new-version-branch.md
Note, that the 3.2 branch in this repo is already created, but the `latest` pointer on the web will be set to it automatically when the tag in Desktop is set. This means, that in the docs homepage, `latest` will point to 3.1 until the tag in Desktop is set accordingly. When merging this PR, 3.0 will be dropped from the web but is available via pdf as usual.
Note, this PR must be merged before the 3.2 tag in Desktop is set to avoid a 404 for `latest`.
Note …
> Changes necessary for 3.2

- modules/ROOT/pages/installing.adoc
Fixes #373 (Remove pre-3.0 AppImage instructions)
Backport to 3.2
> Update AppImage-specific insructions for upcoming 3.2 release

- modules/ROOT/pages/advanced_usage/command_line_client.adoc
- modules/ROOT/pages/advanced_usage/configuration_file.adoc
- modules/ROOT/pages/advanced_usage/environment_variables.adoc
- modules/ROOT/pages/advanced_usage/low_disk_space.adoc
- modules/ROOT/pages/appendices/architecture.adoc
- modules/ROOT/pages/appendices/building.adoc
- modules/ROOT/pages/appendices/guitest.adoc
- modules/ROOT/pages/appendices/troubleshooting.adoc
- modules/ROOT/pages/automatic_updater.adoc
- modules/ROOT/pages/conflicts.adoc
- modules/ROOT/pages/faq.adoc
- modules/ROOT/pages/filenames.adoc
- modules/ROOT/pages/installing.adoc
- modules/ROOT/pages/navigating.adoc
- modules/ROOT/pages/vfs.adoc
- modules/ROOT/pages/web_app.adoc
**This is no content change !**
When using the attribute `:description:` which creates a meta tag in htm for search engines when rendered, you need to use two rules:
* It must be under the section header, not in aprticular order, but without a blank line above
* You must not use any links or attributes like `xref:{url}[text]` - will not get resolved and taken as it is
Found by chance. This PR corrects this for the docs-client-desktop repo.
This will now make search engines print predefined text more likely than before when returning search results.
Backport to 3.2 and 3.1
> Move and update the description attribute to the correct place

- modules/ROOT/pages/installing.adoc
We ceased providing packages for this distribution a while ago. The 3.2 release does not provide any packages for this distribution.
Backport to master
> Ubuntu 21.10 has become end of life

- modules/ROOT/pages/advanced_usage/environment_variables.adoc
Seems this got lost over time…
Related:
https://github.com/owncloud/client/issues/3834
> Bring back lost OCC_UPDATE_URL

- .drone.star
- site.yml
These are the changes necessary to finalize the creation of the 4.0 branch.
The 4.0 branch is already pushed and prepared and is included in the branch protection rules.
When 4.0 (Desktop) is finally out, the 3.1 branch can be archived, see step 4 in https://github.com/owncloud/docs-client-desktop/blob/master/docs/new-version-branch.md
Note, that the 4.0 branch in this repo is already created, but the `latest` pointer on the web will be set to it automatically when the tag in Desktop is set. This means, that in the docs homepage, `latest` will point to 3.2 until the tag in Desktop is set accordingly. When merging this PR, 3.1 will be dropped from the web but is available via pdf as usual.
Note, this PR must be merged before the 4.0 tag in Desktop is set to avoid a 404 for `latest`.
Note …
> Changes necessary for desktop 4.0

- .drone.star
- docs/new-version-branch.md
- site.yml
These are the changes necessary to finalize the creation of the 4.1 branch.
The 4.1 branch is already pushed and prepared and is included in the branch protection rules.
When 4.1 (Desktop) is finally out, the 3.2 branch can be archived, see step 4 in https://github.com/owncloud/docs-client-desktop/blob/master/docs/new-version-branch.md
Note, that the 4.1 branch in this repo is already created, but the `latest` pointer on the web will be set to it automatically when the tag in Desktop is set. This means, that in the docs homepage, `latest` will point to 4.0 until the tag in Desktop is set accordingly. When merging this PR, 3.2 will be dropped from the web but is available via pdf as usual.
Note, this PR must be merged before the 4.1 tag in Desktop is set to avoid a 404 for `latest`.
Note …
> Changes necessary for 4.1

- modules/ROOT/pages/installing.adoc
@fmoc @HanaGemela that's my plan for the customer announcement for the branded 4.1 release
(based on https://cloud.owncloud.com/index.php/f/5870330)
Backport: 4.1
> System requirements updated for 4.1 release

- modules/ROOT/pages/advanced_usage/command_line_client.adoc
- modules/ROOT/pages/advanced_usage/command_line_parameters.adoc
Fixes: #427 ([4.1] [owncloudcmd] from [AppImage])
This PR implements how to use `owncloudcmd` when the Desktop App is installed as AppImage.
Additionally some cleanups and corrections have been made that are aligned with options, arguments, descriptions and commands.
Backport to 4.1 only
> Using owncloudcmd from AppImage

- modules/ROOT/pages/appendices/building.adoc
> Fix broken link

- modules/ROOT/pages/advanced_usage/command_line_client.adoc
Fixes: #404 (.netrc support dropped (for 5.0))
As the title says...
NO Backport, master only.
> Drop .netrc support

- modules/ROOT/pages/using.adoc
References #460 
For unknown reasons, the change did not make it into the main PR. The backports are already fixed.
> Update using.adoc - fix missing commit

- .drone.star
The drone token is no longer available to PRs, so we cannot find other builds that are in progress and cancel them.
Drop this "feature".
And adjust the drone env variables for the new names.
> [CI] Do not try to cancel previous running builds

- modules/ROOT/pages/installing.adoc
Fixes: #90 (NTFS is mandatory with Windows, FAT (or derivates) are not working properly)
This adds some text to the Windows prerequisites preferring NTFS over FAT.
> Prefer NTFS for Windows

- modules/ROOT/pages/automatic_updater.adoc
Fixes: #406 (Migration from before 2.5 -> 5 needs an intermediate installation of 4.0 (for 5.0))
Add a note in the automatic upgrade guide to take an intermediary step.
No backport.
> Intermediary upgrade step from 2.5 to 5.0 via 4.0

- modules/ROOT/pages/advanced_usage/configuration_file.adoc
- modules/ROOT/pages/faq.adoc
Fixes: #266 (Document the desktop clients query intervals and the impacts)
The terms used were not clear and the text needed improvement for better understanding.
The split of the content and the explanation was based on a discussion with @fmoc (many thanks for the input)
Language review welcomed 😄 
> Clarify terms, query intervals and impacts

- modules/ROOT/pages/advanced_usage/configuration_file.adoc
- modules/ROOT/pages/faq.adoc
> [4.1] [PR 469] Clarify terms, query intervals and impacts

- modules/ROOT/pages/vfs.adoc
Fixes: #130 ([QA] Control WinVFS with Attrib.exe)
Add a description how to use `attrib` to bulk manage file states when using VFS.
> Using attrib.exe to Manage States

- .drone.star
- site.yml
These are the changes necessary to finalize the creation of the 4.2 branch.
The 4.2 branch is already pushed and prepared and is included in the branch protection rules.
When 4.2 (Desktop) is finally out, the 4.0 branch can be archived, see step 4 in https://github.com/owncloud/docs-client-desktop/blob/master/docs/new-version-branch.md
Note, that the 4.2 branch in this repo is already created, but the `latest` pointer on the web will be set to it automatically when the tag in Desktop is set. This means, that in the docs homepage, `latest` will point to 4.1 until the tag in Desktop is set accordingly. When merging this PR, 4.0 will be dropped from the web but is available via pdf as usual.
Note, this PR must be merged before the 4.2 tag in Desktop is set to avoid a 404 for `latest`.
Note …
> Changes necessary for 4.2

- modules/ROOT/pages/installing.adoc
No longer tech preview in 4.1+
Backport to master and 4.2
> Add Apple ARM64 to System Requirements

- modules/ROOT/pages/web_app.adoc
References: https://github.com/owncloud/docs-server/issues/1043 (Document core: App Registry)
With oC Server 10.13 that introduced an app registry, web apps in the desktop are now available by both products. This PR "neutralizes" the text to be independed of the backend used.
Note that oC Server has not only office apps but also drawio, therefore neutralizing to web apps where possible.
Note that the referenced issue is not fixed by merging this PR as it needs more PR's covering different manuals.
Backport to 4.1 and 4.2
> Adapt Office Web Apps page

- .drone.star
- docs/new-version-branch.md
- site.yml
These are the changes necessary to finalize the creation of the 5.0 branch.
The 5.0 branch is already pushed and prepared and is included in the branch protection rules.
When 5.0 (Desktop) is finally out, the 4.1 branch can be archived, see step 4 in https://github.com/owncloud/docs-client-desktop/blob/master/docs/new-version-branch.md
Note, that the 5.0 branch in this repo is already created, but the `latest` pointer on the web will be set to it automatically when the tag in Desktop is set. This means, that in the docs homepage, `latest` will point to 4.2 until the tag in Desktop is set accordingly. When merging this PR, 4.1 will be dropped from the web but is available via pdf as usual.
Note, this PR must be merged before the 5.0 tag in Desktop is set to avoid a 404 for `latest`.
Note …
> Changes necessary for 5.0

- modules/ROOT/pages/installing.adoc
Fixes #512 (Install gnome-extensions-app step missing in docs)
* Separate Debian and Redhad based distros
* Add commands for RedHat based distros to properly install `gnome shell extensions appindicator`
(see referenced issue AND its links for details)
* Make the common block also a part of the list
Locally built and renderd, looks fine.
Backport to 5.0 and 4.2
> Fix missing gnome shell extensions appindicator for Redhat distros

- package.json
- yarn.lock
Backport of PR #525
Necessary for local builds only.
> [5.0] [PR 525] Bump @asciidoctor/core from 2.2.6 to 3.0.2

- .drone.star
- site.yml
These are the changes necessary to finalize the creation of the 5.1 branch.
The 5.1 branch is already pushed and prepared and is included in the branch protection rules.
When 5.1 (Desktop) is finally out, the 4.1 branch can be archived, see step 4 in https://github.com/owncloud/docs-client-desktop/blob/master/docs/new-version-branch.md
Note, that the 5.1 branch in this repo is already created, but the `latest` pointer on the web will be set to it automatically when the tag in Desktop is set. This means, that in the docs homepage, `latest` will point to 5.0 until the tag in Desktop is set accordingly. When merging this PR, 4.1 will be dropped from the web but is available via pdf as usual.
Note, this PR must be merged before the 5.x tag in Desktop is set to avoid a 404 for `latest`.
Note …
> Changes necessary for 5.1

- .drone.star
- site.yml
These are the changes necessary to finalize the creation of the 5.2 branch.
The 5.2 branch is already pushed and prepared and is included in the branch protection rules.
When 5.2 (Desktop) is finally out, the 5.0 branch can be archived, see step 4 in https://github.com/owncloud/docs-client-desktop/blob/master/docs/new-version-branch.md
Note, that the 5.2 branch in this repo is already created, but the `latest` pointer on the web will be set to it automatically when the tag in Desktop is set. This means, that in the docs homepage, `latest` will point to 5.1 until the tag in Desktop is set accordingly. When merging this PR, 5.0 will be dropped from the web but is available via pdf as usual.
Note, this PR must be merged before the 5.2 tag in Desktop is set to avoid a 404 for `latest`.
Note …
> Changes necessary for Desktop 5.2

- ext-antora/generate-index.js
> [5.2] [PR 598] Fix command typo in generate-index.js

- .drone.star
These are the changes necessary to finalize the creation of the 5.3 branch.
* The 5.3 branch is already pushed and prepared and is included in the branch protection rules.
* When 5.3 is finally out, the 5.1 branch can be archived, see step 3 in [Create a New Version Branch](https://github.com/owncloud/docs-client-desktop/blob/master/docs/new-version-branch.md)
* Note, that the 5.3 branch in this repo is already created, but the `latest` pointer on the web will be set to it automatically when the tag in Client is set. This means, that in the docs homepage, `latest` will point to 5.2 until the tag in Client is set accordingly. When merging this PR, 5.1 will be dropped from the web.
* Note that this PR must be merged **before** the 5.3 tag in Client is set to avoid a 404 for `latest`.
* Note …
> Changes necessary for Desktop 5.3

- modules/ROOT/pages/automatic_updater.adoc
References: https://github.com/owncloud/docs-server/pull/1440 (Remove remaining hardcoded links to branding)
This PR removes remaining hardcoded links to branding. These links were made as html links and not as xref thats why the got missed in the first run.
Backport to 5.2 and 5.3
> Remove remaining hardcoded links to branding

- modules/ROOT/pages/installing.adoc
This PR fixes an issue formatting some text to italic that contains a comma which needs special treatment according to the Antora docs. I have overseen this when creating the docs as this results in an underline printed that is hard to see. Now, the text is renderd italic properly.
Backport to 6.0
> Fixing an italic formatting issue
